export default {
    themes: {
        "light": {},
        "dark": {},
        "purple": {
            extend: "light",
            colors: {
                background: "#F7F1FF",
                foreground: "#000000",
                primary: {
                    50: "#F2E6F9",
                    100: "#E1C2F2",
                    200: "#C28FE4",
                    300: "#A65DD7",
                    400: "#8A2BCA",
                    500: "#6F00BD",
                    600: "#59009D",
                    700: "#43007E",
                    800: "#2E005F",
                    900: "#19003F",
                    DEFAULT: "#6F00BD",
                    foreground: "#F7F1FF",
                },
                focus: "#8A2BCA",
            },
            layout: {
                disabledOpacity: "0.3",
                radius: {
                    small: "4px",
                    medium: "6px",
                    large: "8px",
                },
                borderWidth: {
                    small: "1px",
                    medium: "2px",
                    large: "3px",
                },
            },
        },
        "dark-purple": {
            extend: "dark",
            colors: {
                background: "#0D001A",
                foreground: "#ffffff",
                primary: {
                    50: "#3B096C",
                    100: "#520F83",
                    200: "#7318A2",
                    300: "#9823C2",
                    400: "#c031e2",
                    500: "#DD62ED",
                    600: "#F182F6",
                    700: "#FCADF9",
                    800: "#FDD5F9",
                    900: "#FEECFE",
                    DEFAULT: "#DD62ED",
                    foreground: "#ffffff",
                },
                focus: "#F182F6",
            },
            layout: {
                disabledOpacity: "0.3",
                radius: {
                    small: "4px",
                    medium: "6px",
                    large: "8px",
                },
                borderWidth: {
                    small: "1px",
                    medium: "2px",
                    large: "3px",
                },
            },
        },
        "red": {
            extend: "light",
            colors: {
                background: "#FFF1F1",
                foreground: "#000000",
                primary: {
                    50: "#FFEBEB",
                    100: "#FFCFCF",
                    200: "#FFA1A1",
                    300: "#FF7373",
                    400: "#FF4545",
                    500: "#FF1717",
                    600: "#DF1515",
                    700: "#BF1212",
                    800: "#9F1010",
                    900: "#7F0D0D",
                    DEFAULT: "#FF1717",
                    foreground: "#FFFFFF",
                },
                focus: "#FF4545",
            },
            layout: {
                disabledOpacity: "0.3",
                radius: {
                    small: "4px",
                    medium: "6px",
                    large: "8px",
                },
                borderWidth: {
                    small: "1px",
                    medium: "2px",
                    large: "3px",
                },
            },
        },
        "dark-red": {
            extend: "dark",
            colors: {
                background: "#1A0000",
                foreground: "#ffffff",
                primary: {
                    50: "#3C0C0C",
                    100: "#5C1818",
                    200: "#7C2424",
                    300: "#9C3030",
                    400: "#BC3C3C",
                    500: "#DC4848",
                    600: "#EC5454",
                    700: "#FC6060",
                    800: "#FC8C8C",
                    900: "#FCA8A8",
                    DEFAULT: "#DC4848",
                    foreground: "#ffffff",
                },
                focus: "#FC6060",
            },
            layout: {
                disabledOpacity: "0.3",
                radius: {
                    small: "4px",
                    medium: "6px",
                    large: "8px",
                },
                borderWidth: {
                    small: "1px",
                    medium: "2px",
                    large: "3px",
                },
            },
        },
        "orange": {
            extend: "light",
            colors: {
                background: "#FFF4E6",
                foreground: "#000000",
                primary: {
                    50: "#FFF8ED",
                    100: "#FFEBD1",
                    200: "#FFDAA3",
                    300: "#FFC975",
                    400: "#FFB747",
                    500: "#FFA519",
                    600: "#E69517",
                    700: "#CC8515",
                    800: "#B37513",
                    900: "#996510",
                    DEFAULT: "#FFA519",
                    foreground: "#FFFFFF",
                },
                focus: "#FFB747",
            },
            layout: {
                disabledOpacity: "0.3",
                radius: {
                    small: "4px",
                    medium: "6px",
                    large: "8px",
                },
                borderWidth: {
                    small: "1px",
                    medium: "2px",
                    large: "3px",
                },
            },
        },
        "dark-orange": {
            extend: "dark",
            colors: {
                background: "#1A0D00",
                foreground: "#ffffff",
                primary: {
                    50: "#3C1B00",
                    100: "#5C2900",
                    200: "#7C3700",
                    300: "#9C4500",
                    400: "#BC5300",
                    500: "#DC6100",
                    600: "#EC6D00",
                    700: "#FC7900",
                    800: "#FC9500",
                    900: "#FCB100",
                    DEFAULT: "#DC6100",
                    foreground: "#ffffff",
                },
                focus: "#FC7900",
            },
            layout: {
                disabledOpacity: "0.3",
                radius: {
                    small: "4px",
                    medium: "6px",
                    large: "8px",
                },
                borderWidth: {
                    small: "1px",
                    medium: "2px",
                    large: "3px",
                },
            },
        },

    }
};
